### ISSUE TITLE
How To Use This Action

### ISSUE THREAD

**Issue by rKinson** [neenjaw/compile-mermaid-markdown-action#2]
@neenjaw 

Can I use this action within my repo wiki and/or pages?

If yes, how do I enable this action?

**Comment by neenjaw** [comment]
**EDIT** - I have fixed the code example to be the newest working example.

---

It can be used easily for github pages.  Test this out in a test-repository, but I think this will get you going:

1. [Create a github pages site](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site)
2. in the repository root, create a folder `.github` with a folder inside named `workflows`
3. create a file `compile_mermaid.yml` with the contents:

```yaml
name: 'Compile Mermaid'

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"
    - name: mermaid files changed
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: compile mermaid
      uses: neenjaw/compile-mermaid-markdown-action@0.2.0
      with:
        files: ${{ steps.getfile.outputs.files }}
        output: 'output'
      env:
        HIDE_CODEBLOCKS: 1
        ABSOLUTE_IMAGE_LINKS: 1

    - name: show changes
      run: |
        git status
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add compiled mermaid
        title: '[MMDC] New mermaid files compiled'
        body: |
          - Auto-generated by [create-pull-request][1]
          [1]: https://github.com/peter-evans/create-pull-request
        labels: automated pr
        assignees: rKinson
        reviewers: rKinson
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
```
