### ISSUE TITLE
Multiple file compilation broken

### ISSUE THREAD

**Issue by rsullivan00** [neenjaw/compile-mermaid-markdown-action#35]
When I have two files modified, the filenames seem to be passed to the shell script as a single argument, which causes no files to compile.

Here's the relevant part of my Action output, after modifying 
- `docs/test_diagram.mmd`
- `docs/test_inline_diagram.md`

```bash
/usr/bin/docker run --name namehere --label 12345 --workdir /github/workspace --rm -e HIDE_CODEBLOCKS -e ABSOLUTE_IMAGE_LINKS -e OUTPUT_FILE_TYPE -e INPUT_FILES -e INPUT_OUTPUT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/MyProject/MyProject":"/github/workspace" 8a33c1:a5c40aaebed54d0db56d5b359432296e  "docs/assets" "docs/test_diagram.mmd docs/test_inline_diagram.md"
# Using MMDC version 8.9.2
# Got output path: docs/assets
# Filetype: png
```

If I instead change one of the diagrams, the compilation succeeds, since the `$@` expansion is unaffected.

Any idea if this is a breaking change from an Actions update? My runner version is `2.278.0`.

Workflow file
```yml
name: 'Compile Mermaid'

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.mmd'
      - '**/*.md'
      - ".github/workflows/mermaid.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mmd$' -e '.*\.mermaid$' | xargs)"

      - name: md files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.1
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'docs/assets'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "png"

      - name: show changes
        run: |
          git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add compiled mermaid
          title: '[MMDC] New mermaid files compiled'
          body: |
            - Mermaid compiled by [compile-mermaid-markdown-action][1]
            - PR Auto-generated by [create-pull-request][2]

            [1]: https://github.com/neenjaw/compile-mermaid-markdown-action
            [2]: https://github.com/peter-evans/create-pull-request
          labels: report, automated pr
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
```
