### ISSUE TITLE
Syntax Error InGraph

### ISSUE THREAD

**Issue by philipduan** [neenjaw/compile-mermaid-markdown-action#39]
Hi,

I have this mermaid graph 

```
flowchart LR
  subgraph Create Account By Invitation Flow
    direction LR
    Support-- Invite using \sign-up-as-manager -->Manager-- Invite using /sign-up -->Personal_Trainer & Client
    Personal_Trainer --Invite using /sign-up--> Client
  end
```

with this workflow file
```
name: Update Swagger UI and Compile Mermaid
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.mermaid'
      - '**/*.mmd'
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  updateSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mmd$' -e '.*\.mermaid$' | xargs)"
      - name: mermaid files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.1
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: './docs/UX'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "png"
      - name: show changes
        run: |
          git status
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update swagger-ui to ${{ steps.swagger-ui.outputs.release_tag }} and Add compiled mermaid
          title: 'Update SwaggerUI to ${{ steps.swagger-ui.outputs.release_tag }} and New mermaid files compiled'
          body: |
            Updates [swagger-ui][1] to ${{ steps.swagger-ui.outputs.release_tag }}
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/swagger-api/swagger-ui
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, report, automated pr
```

I am not sure why but this is the result i have
![docs_UX_authentication-md-1](https://user-images.githubusercontent.com/32302270/141673313-1893c7af-bd3d-469c-8a22-f597d0a1c1b7.png)

Can anyone give me a hand? Thanks
